exclude: ['README.md']
permalink: /blog/:title/

title: Parametric Thoughts
tagline: Homepage of Nikolai Janakiev
description: MSc Applied Image and Signal Processing // Geometric Modelling / Signal Processing / Data Analysis / Data Visualization
url: 'http://janakiev.com'
author: njanakiev

twitter:
  username: njanakiev

social:
  name: Nikolai Janakiev
  links:
    - https://twitter.com/njanakiev
    - https://github.com/njanakiev
    - https://www.linkedin.com/in/nikolai-janakiev/

tilurl: 'http://til.janakiev.com' 
twitterurl: 'https://twitter.com/njanakiev'
githuburl: 'https://github.com/njanakiev'
paramcookieurl: 'http://parametriccookie.tumblr.com/'

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
