exclude: ['README.md']
permalink: /:categories/:title/

title: Parametric Thoughts
tagline: Homepage of Nikolai Janakiev
description: MSc Applied Image and Signal Processing // Data Science / Data Visualization / Signal Processing / Geometric Modelling
url: 'http://janakiev.com'

author: 
  name: Nikolai Janakiev
  twitter: njanakiev

twitter:
  username: njanakiev

social:
  name: Nikolai Janakiev
  links:
    - https://twitter.com/njanakiev
    - https://github.com/njanakiev
    - https://medium.com/@njanakiev
    - https://www.linkedin.com/in/nikolai-janakiev/

twitterurl: 'https://twitter.com/njanakiev'
githuburl: 'https://github.com/njanakiev'
linkedinurl: 'https://www.linkedin.com/in/nikolai-janakiev/'

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
