exclude: ['README.md']
permalink: /blog/:title/

title: Parametric Thoughts
tagline: A Blog by Nikolai Janakiev
description: MA Student in Applied Image and Signal Processing // Data Visualization / 3D / Open Data
url: 'http://janakiev.com'
author: Nikolai Janakiev
twitter:
  username: njanakiev

tilurl: 'http://til.janakiev.com' 
twitterurl: 'https://twitter.com/njanakiev'
githuburl: 'https://github.com/njanakiev'

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed